import nx from "@nx/eslint-plugin";
import baseConfig from "../../eslint.config.mjs";

export default [
    ...baseConfig,
    ...nx.configs["flat/react"],
    {
        files: [
            "**/*.ts",
            "**/*.tsx",
            "**/*.js",
            "**/*.jsx"
        ],
        // Override or add rules here
        rules: {}
    },
    {
        ignores: [
            ".expo",
            "web-build",
            "cache",
            "dist",
            "**/out-tsc",
            // Native projects are generated by `expo prebuild` (CNG) and gitignored;
            // their template files are not our source to lint.
            "ios",
            "android"
        ]
    }
];
